### ISSUE TITLE
How to start a TFTP Server in ptxdist 

### ISSUE THREAD

**Issue by amsthecodder** [clemensg/ptxdist#1]
tftp server configuration file in inetd.confd contains:

tftp dgram udp wait nobody /sbin/tftpd tftpd -l /var/tftp

Changed the permissions of tftp folder in var to 777.
Changed the ownership of tftp folder in var to nobody.

Tried to start by executing :  

systemctl start /sbin/tftpd

Still it's not working.
Any guidance is greatly appreciated.
Thank you.

**Comment by clemensg** [comment]
Hi,

this is just a mirror of the repository at git.pengutronix.de
For questions about PTXdist, please use the mailing list, see http://www.pengutronix.de/en/software/projects.html

About TFTP: If you want to have tftpd running on the target, you need a /usr/lib/systemd/system/tftpd.service file, afaik it is not shipped, so you have to create one yourself. If you want to start a systemd service, use systemctl start tftpd.service (of course the service file needs to exist for that)
Have a look at systemd docs and you can start with service files from distros like ArchLinux (See for example https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/tftp-hpa) and modify them.
If you want tftpd running on the host (for development), you can just start it directly with your plaform-dir/images directory without systemd.
